const Work = [
  {
    id: 1,
    mainImage: "/images/mlpb/2.png",
    img: [
      "/images/mlpb/2.png",
      "/images/mlpb/3.png",
      "/images/mlpb/4.png",
      "/images/mlpb/5.png",
      "/images/mlpb/6.png",
      "/images/mlpb/7.png",
      "/images/mlpb/8.png",
      "/images/mlpb/9.png",
      "/images/mlpb/10.png",
      "/images/mlpb/11.png",
      "/images/mlpb/12.png",
      "/images/mlpb/13.png",
      "/images/mlpb/14.png",
      "/images/mlpb/15.png",
      "/images/mlpb/1.png",
    ],
    features: [
      "Signup",
      "Login",
      "Landing Page",
      "My Collection",
      "Wallet",
      "Create",
      "Marketplace",
      "About",
      "Legal",
      "Setting",
    ],
    technologies: ["Next JS", "TypeScript", "CSS", "Grommet"],
    title: "MLPB Armory",
    description:
      "A blockchain project in which I contributed for frontend development. I have built the minting portal for creating an NFT and email templates from scratch and worked on UI fixes that has responsiveness issues and other bugs. Integrated some APIs as well.",
    category: "business",
    liveLink: "https://dev.mlpbarmory.com/",
  },
  {
    id: 2,
    mainImage: "/images/finarch/2.png",
    img: [
      "/images/finarch/2.png",
      "/images/finarch/3.png",
      "/images/finarch/4.png",
      "/images/finarch/5.png",
      "/images/finarch/6.png",
      "/images/finarch/1.png",
    ],
    features: [
      "Home",
      "Get a Quote",
      "About",
      "Team",
      "Projects",
      "News",
      "Career",
      "Contact",
      "Terms and Conditions",
      "Privacy Policy",
    ],
    technologies: ["React JS", "JavaScript", "CSS", "Material UI"],
    title: "Finarch",
    description:
      "Finarch is an architectural website which is built in React js. Home page displays a slider of successful work. The project page shows the work which are completed or under construction. Fully responsive over all devices. Used Material UI for achieving the exact client requirements.",
    category: "business",
    liveLink: "https://www.finarch.co/",
    codeLink: "https://github.com/zunairaasif/Finarch",
  },
  {
    id: 3,
    mainImage: "/images/altcode/1.png",
    img: [
      "/images/altcode/2.png",
      "/images/altcode/3.png",
      "/images/altcode/4.png",
      "/images/altcode/5.png",
      "/images/altcode/6.png",
      "/images/altcode/7.png",
      "/images/altcode/8.png",
      "/images/altcode/1.png",
    ],
    features: ["Home", "Services", "About", "Contact"],
    technologies: [
      "Next JS",
      "Material UI",
      "CSS",
      "Framer Motion",
      "SketchFab",
      "React Three Fiber",
      "Formik",
      "Yup",
    ],
    title: "AltCode Labs",
    description:
      "It's a software company's website built in Next.js. It contains animations using Framer Motion and React Three Fiber. Worked with Material UI for full responsiveness. Implemented Formik & Yup for form validation on contact page.",
    category: "business",
    liveLink: "https://www.altcodelabs.com/",
    codeLink: "https://github.com/zunairaasif/Altcode",
  },
  {
    id: 4,
    mainImage: "/images/florish/3.png",
    img: [
      "/images/florish/2.png",
      "/images/florish/3.png",
      "/images/florish/4.png",
      "/images/florish/5.png",
      "/images/florish/6.png",
      "/images/florish/1.png",
    ],
    features: [
      "Signup",
      "Login",
      "Home",
      "Product",
      "About",
      "Contact",
      "Cart",
    ],
    technologies: ["React JS", "Material UI", "Formik", "Yup"],
    title: "Florish",
    description:
      "Built an e-commerce web application for buying plants. Worked with Formik & Yup for form validation. Used MUI for flexible UI. Worked with React Router v6 for routing and used useQuery & apiSauce for API calls.",
    category: "personal",
    codeLink: "https://github.com/zunairaasif/Flourish",
  },
];

export default Work;
